### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by Quackeh** [Kxnrl/AdvMusicPlayer#11]
I believe I installed all the extensions and requirements however in game when I type !music the menu does come up but when I click "search song" nothing happens.

**Comment by penalte** [comment]
https://github.com/Kxnrl/AdvMusicPlayer/issues/10

**Comment by Quackeh** [comment]
Yeah I added downloaded the ffmpeg.exe however there are no files in sourcemod/data/music/

**Comment by Kxnrl** [comment]
any errlogs?

**Comment by Quackeh** [comment]
The only errors I can see is "Unknown command: snd_setsoundparam". However I am also unaware if this is even related.

**Comment by Kxnrl** [comment]
no, I mean plugin errors

**Comment by Quackeh** [comment]
none

**Comment by Kxnrl** [comment]
can search song?

**Comment by Quackeh** [comment]
Nope

**Comment by ryusei423** [comment]
I also encountered the same problem. I think this is caused by the unavailability of some functions of the Windows version of steamworks. So I tried many versions of Windows steamworks
I tried to recompile the plug-in with the inc file of the Windows version. It still does not work. Please add the Windows version of the steamworks file

**Comment by Kxnrl** [comment]
[Uploading SteamWorks.ext.dll.zip…]()

**Comment by Kxnrl** [comment]
[SteamWorks.ext.dll.zip](https://github.com/Kxnrl/AdvMusicPlayer/files/5358763/SteamWorks.ext.dll.zip)

**Comment by ryusei423** [comment]
Thank you. . I found that the old 182 version is compatible with some versions of steamworks, and then I encountered the problem of not being able to play. This is caused by the lack of ffmpeg.exe.
I just tried the steamworks you just uploaded and it works well with the latest 187 version. thank you very much.
